version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/lib/postgresql/logs
    # command: /bin/bash -c "postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/logs"

volumes:
  postgres_data:
  postgres_logs:
